# This is a basic workflow to help you get started with Actions

# Workflow name
name: 'Chromatic'

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: yarn
      - name: build chromatic
        run: yarn chromatic
      # 👇 Adds Chromatic as a step in the workflow
      # - name: Publish to Chromatic
      #   uses: chromaui/action@v1
      #   # Chromatic GitHub Action options
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     # 👇 Chromatic projectToken, refer to the manage page to obtain it.
      #     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}